### ISSUE TITLE
Zencash Error, founders reward missing for block template!

### ISSUE THREAD

**Issue by williamsmithza** [s-nomp/s-nomp#51]
Have added Zencash to my pool but when starting up get the following

Error, founders reward missing for block template!

**Comment by Punkoivan** [comment]
Hey @williamsmithza, we have the same errors on some coins but looks like it's false positive.

If your blocks are accepted by network - you definitely have founders rewards.

**Comment by williamsmithza** [comment]
Is there any fix to this ? or you still looking into it ?

**Comment by egyptianbman** [comment]
@williamsmithza there's a 99.9% chance this is caused by misconfiguration. Please go through your configuration and make sure it matches with what's in place in this repo. If so, please provide:
- Your coin configs
- Your pool configs
- Exact error message from the stratum
- Log output from the coin daemon at the time of the error.

**Comment by williamsmithza** [comment]
ok will check it out again and compare

**Comment by tarrenj** [comment]
@williamsmithza Any updates?

**Comment by Gumbees** [comment]
Closing issue due to no response by OP.
